services:
  crawler:
    build: .
    container_name: jobs-crawler
    ports:
      - "8000:8000"
    volumes:
      - /home/nam/composes/workbot/data:/app/data
    environment:
      - SELENIUM_URL=http://chrome:4444
    depends_on:
      - chrome
    networks:
      - n8n-net

  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
    expose:
      - 4444
    shm_size: "2g"
    networks:
      - n8n-net

networks:
  n8n-net:
    external: true
